package reasonix

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/aoagents/agent-orchestrator/backend/internal/domain"
)

// ValidSessionID accepts the portable machine handles generated by Reasonix,
// including legacy timestamp/model names. Synthetic child runners use colon-
// qualified IDs (or the bare fallback role); they must not replace the parent
// session's restore handle or complete its turn.
func ValidSessionID(id string) bool {
	if id == "" || len(id) > 255 || id[0] == '.' || id[0] == '-' || strings.HasSuffix(id, ".") || id == "subagent" || id == "planner" {
		return false
	}
	for _, c := range id {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '_', c == '-', c == '.':
		default:
			return false
		}
	}
	base := strings.ToUpper(strings.SplitN(id, ".", 2)[0])
	if base == "CON" || base == "PRN" || base == "AUX" || base == "NUL" {
		return false
	}
	if len(base) == 4 && (strings.HasPrefix(base, "COM") || strings.HasPrefix(base, "LPT")) && base[3] >= '1' && base[3] <= '9' {
		return false
	}
	return true
}

// HookSessionID reads only the native sessionId field, never compatible aliases
// that could accidentally admit a child/session-shaped payload from elsewhere.
func HookSessionID(payload []byte) string {
	var native struct {
		SessionID string `json:"sessionId"`
	}
	if json.Unmarshal(bytes.TrimPrefix(payload, []byte("\xef\xbb\xbf")), &native) != nil || !ValidSessionID(native.SessionID) {
		return ""
	}
	return native.SessionID
}

// IsMainSessionHook checks the event as well as native parent identity before
// the CLI accepts either activity or resumable-session metadata.
func IsMainSessionHook(event string, payload []byte) bool {
	var native struct {
		Event string `json:"event"`
	}
	if json.Unmarshal(bytes.TrimPrefix(payload, []byte("\xef\xbb\xbf")), &native) != nil || HookSessionID(payload) == "" {
		return false
	}
	for _, spec := range reasonixHookEvents {
		if spec.ao == event {
			return spec.native == native.Event
		}
	}
	return false
}

// DeriveActivityState reduces Reasonix's native observer events. Tool payloads
// have no call ID, so permission requests cannot safely establish a correlated
// blocked state. SessionEnd also fires on /new; process exit stays the runtime
// observer's responsibility. SessionStart is metadata-only and lazy on first
// submission, so it is not evidence that an empty composer is ready.
func DeriveActivityState(event string, payload []byte) (domain.ActivityState, bool) {
	payload = bytes.TrimPrefix(payload, []byte("\xef\xbb\xbf"))
	var native struct {
		Error       string `json:"error"`
		IsInterrupt bool   `json:"isInterrupt"`
	}
	if json.Unmarshal(payload, &native) != nil || !IsMainSessionHook(event, payload) {
		return "", false
	}
	switch event {
	case "user-prompt-submit", "pre-tool-use", "post-tool-use":
		return domain.ActivityActive, true
	case "stop":
		if native.Error == "" && !native.IsInterrupt {
			return domain.ActivityWaitingInput, true
		}
	}
	return "", false
}
